# Generated by Django 6.0 on 2025-12-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Назва курсу")),
                ("description", models.TextField(verbose_name="Опис курсу")),
                (
                    "teacher",
                    models.CharField(max_length=150, verbose_name="Ім'я викладача"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курси",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Назва завдання"),
                ),
                ("description", models.TextField(verbose_name="Опис завдання")),
                ("deadline", models.DateTimeField(verbose_name="Термін виконання")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="main.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завдання",
                "verbose_name_plural": "Завдання",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Назва матеріалу"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="materials/", verbose_name="Файл матеріалу"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис матеріалу"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="main.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матеріал",
                "verbose_name_plural": "Матеріали",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.CharField(max_length=150, verbose_name="Ім'я студента"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="submissions/", verbose_name="Файл здачі"
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Оцінка",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="main.assignment",
                        verbose_name="Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Здача",
                "verbose_name_plural": "Здачі",
            },
        ),
    ]
