# Generated by Django 6.0 on 2025-12-16 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Викладач",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="main.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                upload_to="materials/", verbose_name="Файл матеріалу"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(upload_to="submissions/", verbose_name="Файл здачі"),
        ),
    ]
